using System.Runtime.InteropServices;
using bOps.Packages.Firewall.Core;
namespace bOps.Packages.Firewall.Windows.Helper;
internal static class WindowsFirewallComCollector
{
    private const int Domain=1, Private=2, Public=4;
    internal static FirewallStatusSnapshot Status(){object? policy=null;try{policy=Create();IReadOnlyList<FirewallProfile> profiles=[Profile(policy,"domain",Domain),Profile(policy,"private",Private),Profile(policy,"public",Public)];return new(profiles.All(x=>x.Enabled==true),null,null,profiles,"windows-firewall","HNetCfg.FwPolicy2",true);}catch(Exception ex) when(ex is COMException or InvalidOperationException or MissingMethodException){return new(null,null,null,[],"unavailable","HNetCfg.FwPolicy2",false,ex.Message);}finally{Release(policy);}}
    internal static FirewallRulesSnapshot Rules(){object? policy=null;var rules=new List<FirewallRule>();var truncated=false;try{policy=Create();foreach(var item in (System.Collections.IEnumerable)Property(policy,"Rules")!){if(rules.Count==FirewallLimits.MaximumRows){truncated=true;break;}object rule=item!;try{rules.Add(Map(rule));}finally{Release(rule);}}return new(rules,"windows-firewall","HNetCfg.FwPolicy2",!truncated,truncated);}catch(Exception ex) when(ex is COMException or InvalidOperationException or MissingMethodException){return new(rules,"windows-firewall","HNetCfg.FwPolicy2",false,truncated,ex.Message);}finally{Release(policy);}}
    private static object Create()=>Activator.CreateInstance(Type.GetTypeFromProgID("HNetCfg.FwPolicy2")??throw new InvalidOperationException("HNetCfg.FwPolicy2 is not registered."))!;
    private static FirewallProfile Profile(object p,string name,int mask)=>new(name,(bool)Property(p,"FirewallEnabled",mask)!,Action((int)Property(p,"DefaultInboundAction",mask)!),Action((int)Property(p,"DefaultOutboundAction",mask)!));
    private static FirewallRule Map(object r)=>new("",(string?)Property(r,"Name"),(bool)Property(r,"Enabled")!,Direction((int)Property(r,"Direction")!),Action((int)Property(r,"Action")!),Protocol((int)Property(r,"Protocol")!),Split((string?)Property(r,"LocalAddresses")),Split((string?)Property(r,"RemoteAddresses")),Split((string?)Property(r,"LocalPorts")),Split((string?)Property(r,"RemotePorts")),Profiles((int)Property(r,"Profiles")!),(string?)Property(r,"ApplicationName"),(string?)Property(r,"serviceName"),Interface(Property(r,"Interfaces")),null,"windows-firewall");
    private static object? Property(object target,string name,params object[] arguments)=>target.GetType().InvokeMember(name,System.Reflection.BindingFlags.GetProperty,null,target,arguments);
    private static string Direction(int v)=>v==1?"inbound":v==2?"outbound":"unknown";private static string Action(int v)=>v==1?"block":v==0?"allow":"unknown";private static string Protocol(int v)=>v==6?"tcp":v==17?"udp":v is 1 or 58?"icmp":v==256?"any":"native-unknown";
    private static List<string> Profiles(int mask){var x=new List<string>();if((mask&Domain)!=0)x.Add("domain");if((mask&Private)!=0)x.Add("private");if((mask&Public)!=0)x.Add("public");return x;}private static string[] Split(string? s)=>string.IsNullOrWhiteSpace(s)||s=="*"?[]:s.Split(',',StringSplitOptions.TrimEntries|StringSplitOptions.RemoveEmptyEntries);private static string? Interface(object? value)=>value is Array a?string.Join(',',a.Cast<object?>().Select(x=>x?.ToString()).Where(x=>x is not null)):value?.ToString();private static void Release(object? o){if(o is not null&&Marshal.IsComObject(o))Marshal.FinalReleaseComObject(o);}
}
