[CmdletBinding()]
param(
    [string]$Manifest = 'agentic/_quality/manifests/v1.3-g.json',
    [switch]$RunTests,
    [switch]$SmokeTest,
    [switch]$AllowPendingExternal,
    [switch]$TestSelf,
    [string]$EvidenceDirectory,
    [string]$KnownFailures = 'agentic/_quality/known-failures.json',
    [switch]$VerifyKnownFailures,
    [switch]$CollectPlatformEvidence,
    [switch]$ApplyManifestEnvironment,
    [ValidateSet('windows','linux')][string]$Platform,
    [string]$Output,
    [string]$SourceCommit,
    [switch]$AggregateCiEvidence,
    [string]$LocalReport,
    [string[]]$PlatformEvidence,
    [string]$CiRunId,
    [string]$CiCommit,
    [string]$OutputDirectory,
    [switch]$FinalizeVerified,
    [string]$CiReport,
    [string]$ExpectedCommit,
    [string]$ReportsDirectory,
    [string]$Index,
    [ValidateRange(1,120)][int]$CommandTimeoutMinutes = 30
)
$ErrorActionPreference = 'Stop'
$Categories = @('contractCoverage','negativeBoundaryCoverage','verificationMutationSafety','architectureSecurity','regressionEvidence','traceability')
$Allowed = @('PASS','FAIL','PENDING','SKIP')

function Assert-Quality([bool]$Condition,[string]$Message) { if (-not $Condition) { throw "Self-test failed: $Message" } }
function Read-Json([string]$Path) { Get-Content -Raw -LiteralPath $Path | ConvertFrom-Json }
function Validate-Manifest($m) {
    if (-not $m.criteria) { throw 'Manifest has no criteria.' }
    $ids = @{}
    foreach ($c in $m.criteria) {
        if ($ids.ContainsKey($c.id)) { throw "Duplicate criterion id: $($c.id)" }; $ids[$c.id] = $true
        if ($Categories -notcontains $c.category) { throw "Unknown category: $($c.category)" }
        if ($Allowed -notcontains $c.status) { throw "Invalid status: $($c.status)" }
        foreach ($p in 'id','category','requirement','hardGate','evidence','status') { if ($null -eq $c.$p) { throw "Missing criterion property $p ($($c.id))." } }
    }
    $sum = 0; foreach ($cat in $Categories) { $sum += [double]$m.weights.$cat }
    if ($sum -ne 100) { throw "Category weights must sum to 100 (actual $sum)." }
}
function New-RunDirectory([string]$Root,[string]$Milestone) {
    $safe = $Milestone.ToLowerInvariant().Replace('.','-'); $dir = Join-Path $Root (Join-Path 'artifacts/quality' $safe)
    if (Test-Path $dir) { Remove-Item -LiteralPath $dir -Recurse -Force }
    New-Item -ItemType Directory -Force -Path (Join-Path $dir 'trx') | Out-Null
    New-Item -ItemType Directory -Force -Path (Join-Path $dir 'streams') | Out-Null
    return $dir
}
function Invoke-ProcessAtomically([string]$FileName,[string[]]$CommandArguments,[string]$WorkingDirectory,[string]$OutputDirectory,[int]$TimeoutMinutes,[hashtable]$Environment=@{}) {
    New-Item -ItemType Directory -Force -Path $OutputDirectory | Out-Null
    $stdoutPath = Join-Path $OutputDirectory 'stdout.txt'; $stderrPath = Join-Path $OutputDirectory 'stderr.txt'
    $psi = [Diagnostics.ProcessStartInfo]::new(); $psi.FileName=$FileName; $psi.WorkingDirectory=$WorkingDirectory; $psi.UseShellExecute=$false; $psi.CreateNoWindow=$true; $psi.RedirectStandardOutput=$true; $psi.RedirectStandardError=$true
    foreach ($arg in $CommandArguments) { [void]$psi.ArgumentList.Add($arg) }
    foreach ($name in $Environment.Keys) { $psi.Environment[$name] = [string]$Environment[$name] }
    $p = [Diagnostics.Process]::new(); $p.StartInfo=$psi; $started=$false; $timedOut=$false; $infra=$null; $exit=$null; $out=''; $err=''
    try {
        $started=$p.Start(); if (-not $started) { throw 'Process.Start returned false.' }
        $outTask=$p.StandardOutput.ReadToEndAsync(); $errTask=$p.StandardError.ReadToEndAsync()
        if (-not $p.WaitForExit($TimeoutMinutes*60*1000)) { $timedOut=$true; $infra="Process timed out after $TimeoutMinutes minute(s): $FileName $($CommandArguments -join ' ')"; try { $p.Kill($true) } catch { }; $p.WaitForExit() }
        $out=$outTask.GetAwaiter().GetResult(); $err=$errTask.GetAwaiter().GetResult(); $exit=$p.ExitCode
    } catch { $infra="Process infrastructure failure: $($_.Exception.Message)" } finally { $p.Dispose() }
    Set-Content -LiteralPath $stdoutPath -Value $out -Encoding utf8; Set-Content -LiteralPath $stderrPath -Value $err -Encoding utf8
    [pscustomobject]@{ completed=($started -and -not $timedOut -and $null -ne $exit); exitCode=$exit; timedOut=$timedOut; infrastructureError=$infra; stdout=$stdoutPath; stderr=$stderrPath; command=("$FileName $($CommandArguments -join ' ')") }
}
function Read-CompleteTrx([string]$Path) {
    try { [xml]$x=Get-Content -Raw -LiteralPath $Path } catch { return [pscustomobject]@{valid=$false;error="Malformed TRX: $Path"} }
    $results=@($x.TestRun.Results.UnitTestResult)
    if (-not $x.TestRun -or -not $x.TestRun.Results -or $results.Count -eq 0 -or -not $x.TestRun.TestDefinitions -or -not $x.TestRun.ResultSummary) { return [pscustomobject]@{valid=$false;error="Incomplete TRX: $Path"} }
    [pscustomobject]@{valid=$true;path=$Path;results=$results;definitions=@($x.TestRun.TestDefinitions.UnitTest)}
}
function Get-CombinedTests($TrxFiles) {
    $all=@(); $errors=@(); foreach($f in $TrxFiles){$t=Read-CompleteTrx $f;if($t.valid){$all += $t.results}else{$errors += $t.error}}
    [pscustomobject]@{results=$all;errors=$errors;total=$all.Count;passed=@($all|? outcome -eq Passed).Count;failed=@($all|?{$_.outcome -in @('Failed','Error')}).Count;skipped=@($all|?{$_.outcome -in @('NotExecuted','Skipped')}).Count}
}
function Read-KnownRegistry([string]$Path) {
    $r=Read-Json $Path; if(-not $r.entries){throw 'Known-failure registry has no entries.'};$ids=@{};foreach($e in $r.entries){foreach($p in 'test','classification','evidence','introducedBefore','isolatedExpectedToPass','testProject'){if($null -eq $e.$p){throw "Known-failure entry missing $p."}};if($ids.ContainsKey($e.test)){throw "Duplicate known-failure test: $($e.test)"};$ids[$e.test]=$true};return @($r.entries)
}
function Get-MilestoneSlug($m) { $s=$m.milestone.ToLowerInvariant() -replace '[^a-z0-9]+','-';$s.Trim('-') }
function Read-ActiveMilestone([string]$Root) {
    $a=Read-Json (Join-Path $Root 'agentic/_quality/active-milestone.json')
    if($a.slug -notmatch '^[a-z0-9]+(?:-[a-z0-9]+)*$'){throw 'Active milestone slug is not safe.'}
    foreach($p in @($a.manifest,$a.localReport)){if([IO.Path]::IsPathRooted($p)){throw 'Active milestone paths must be repository-relative.'};if(-not (Test-Path (Join-Path $Root $p))){throw "Active milestone path does not exist: $p"}}
    return $a
}
function Get-PlatformCriteria($m,[string]$p) { @($m.criteria|?{$_.evidence.type -eq 'platform evidence' -and $_.evidence.platform -eq $p}) }
function Ensure-OutputParent([string]$Path) {
    $parent = Split-Path -Parent -Path $Path
    if ($parent) { New-Item -ItemType Directory -Force -Path $parent | Out-Null }
}
function Get-PlatformEnvironment($criterion,[bool]$Apply) {
    $env = @{}
    if (-not $criterion.evidence.environment) { return $env }
    if ($criterion.evidence.platform -eq 'Linux' -and -not $Apply) { return $env }
    if ($criterion.evidence.platform -eq 'Windows' -and $criterion.evidence.environment.BOPS_RUN_REAL_SCHEDULER_TESTS -eq '1') {
        $principal = New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent())
        if (-not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) { return $env }
    }
    foreach ($property in $criterion.evidence.environment.PSObject.Properties) {
        if ($property.Name -notmatch '^[A-Z_][A-Z0-9_]*$' -or $null -eq $property.Value -or $property.Value -is [System.Array]) { throw "Invalid trusted platform environment declaration: $($property.Name)" }
        $env[$property.Name] = [string]$property.Value
    }
    return $env
}
function Get-TrxIdentityResults($trxFiles,[string]$Identity) {
    $matches=@();$errors=@()
    foreach($file in $trxFiles){$doc=Read-CompleteTrx $file;if(-not $doc.valid){$errors += $doc.error;continue};foreach($result in $doc.results){$definition=@($doc.definitions|? id -eq $result.testId|Select-Object -First 1);$declared='';if($definition){$class=[string]$definition.TestMethod.className;$method=[string]$definition.TestMethod.name;if($class -and $method){$declared="$class.$method"}else{$declared=[string]$definition.name}};if($declared -eq $Identity -or [string]$result.testName -eq $Identity){$matches += $result}}}
    [pscustomobject]@{results=$matches;errors=$errors}
}
function Get-PlatformStatus($process,$identityResults,[string]$stdout) {
    if(-not $process.completed -or $identityResults.errors.Count){return [pscustomobject]@{status='BLOCKED';reason='Process or TRX infrastructure failure.'}}
    if($identityResults.results.Count -eq 0){return [pscustomobject]@{status='BLOCKED';reason='Required test identity declared by manifest was not found.'}}
    if(@($identityResults.results|? outcome -eq Passed).Count -eq 1 -and $process.exitCode -eq 0){return [pscustomobject]@{status='PASS';reason=$null}}
    if(@($identityResults.results|? outcome -in @('Failed','Error')).Count){return [pscustomobject]@{status='FAIL';reason='Required platform test failed.'}}
    if(@($identityResults.results|? outcome -in @('NotExecuted','Skipped')).Count){return [pscustomobject]@{status='PENDING';reason='Test explicitly skipped by platform/capability/privilege gate.'}}
    return [pscustomobject]@{status='BLOCKED';reason='Test did not produce an expected result.'}
}
function Get-LocalQualityPlatform() { if($IsWindows){'Windows'}elseif($IsLinux){'Linux'}else{'Unknown'} }
function Get-PlatformCriterionStatus($criterion,[string]$localPlatform,$result) {
    if([string]$criterion.evidence.platform -ne $localPlatform){return [pscustomobject]@{status='PENDING';outcome='HOST_MISMATCH'}}
    if($result.passed){return [pscustomobject]@{status='PASS';outcome='PASS'}}
    if($result.exists -and $result.ran){return [pscustomobject]@{status='FAIL';outcome='FAIL'}}
    [pscustomobject]@{status='PENDING';outcome=[string]$result.outcome}
}
function Read-PlatformArtifact([string]$Path,$m,[string]$p,[string]$commit) {
    try{$a=Read-Json $Path}catch{return [pscustomobject]@{valid=$false;error="Malformed platform evidence: $Path"}}
    if($a.milestone -ne $m.milestone -or $a.slug -ne (Get-MilestoneSlug $m) -or $a.platform -ne $p -or $a.sourceCommit -ne $commit){return [pscustomobject]@{valid=$false;error="Platform evidence identity mismatch: $Path"}}
    $expected=@(Get-PlatformCriteria $m $p);$returned=@($a.criteria);$expectedIds=@($expected|% id);$returnedIds=@($returned|% id)
    if($returned.Count -eq 0 -and $expected.Count -gt 0){return [pscustomobject]@{valid=$false;error="Platform evidence is missing expected criteria: $Path"}}
    if(@($returnedIds|Group-Object|? Count -gt 1).Count -gt 0){return [pscustomobject]@{valid=$false;error="Platform evidence has duplicate criteria: $Path"}}
    foreach($c in $returned){if($Allowed -notcontains $c.status -or -not $c.id -or $expectedIds -notcontains $c.id){return [pscustomobject]@{valid=$false;error="Invalid or unknown platform criterion: $Path"}}}
    foreach($id in $expectedIds){if($returnedIds -notcontains $id){return [pscustomobject]@{valid=$false;error="Platform evidence is missing criterion ${id}: $Path"}}}
    [pscustomobject]@{valid=$true;artifact=$a}
}
function Get-ScoreSummary($criteria,$weights) {
    $cats=[ordered]@{};$n=0;$d=0;foreach($cat in $Categories){$rows=@($criteria|? category -eq $cat);$p=@($rows|? status -eq PASS).Count;$f=@($rows|? status -eq FAIL).Count;$q=@($rows|? status -eq PENDING).Count;$s=@($rows|? status -eq SKIP).Count;$score=if($p+$f){[math]::Round(100*$p/($p+$f),2)}else{$null};$cats[$cat]=[ordered]@{passed=$p;failed=$f;pending=$q;skipped=$s;score=$score;weight=[double]$weights.$cat};if($null-ne$score){$n+=$score*[double]$weights.$cat;$d+=[double]$weights.$cat}};[pscustomobject]@{categories=$cats;score=if($d){[math]::Round($n/$d,2)}else{$null}}
}
function Write-Projection([string]$Path,$r) {
    $l=@("# $($r.milestone) Quality Report",'',"Status: $($r.qualityStatus)","Local status: $($r.localStatus)","Repository health: $($r.repositoryHealth)","Milestone regression: $($r.milestoneRegressionStatus)",'',"Final score: $($r.finalQualityScore)","Provisional score: $($r.provisionalScore)","Known failures observed: $(@($r.knownFailuresObserved).Count)","New failures: $(@($r.newFailures).Count)","Known failures unconfirmed: $(@($r.knownFailuresUnconfirmed).Count)",'', '## Pending evidence');$l+=@($r.pendingEvidence|%{"- $_"});Set-Content -LiteralPath $Path -Value $l -Encoding utf8
}
function Invoke-PlatformCollection {
    $m=Read-Json $Manifest;Validate-Manifest $m;if(-not $Platform -or -not $Output -or -not $SourceCommit){throw 'Platform collection requires -Platform, -Output and -SourceCommit.'};$criteria=Get-PlatformCriteria $m $Platform;$root=Join-Path ([IO.Path]::GetTempPath()) ('bops-platform-'+$Platform);if(Test-Path $root){Remove-Item $root -Recurse -Force};New-Item -ItemType Directory -Force -Path $root|Out-Null;$rows=@();$blocked=$false;$failed=$false
    foreach($c in $criteria){$slot=Join-Path $root $c.id;$args=@('test',(Join-Path (Get-Location).Path $c.evidence.testProject),'--configuration','Release','--no-build','--filter',('FullyQualifiedName='+$c.evidence.testName),'--logger','trx','--results-directory',$slot,'--nologo');$childEnvironment=Get-PlatformEnvironment $c $ApplyManifestEnvironment;$fileName='dotnet';$childArgs=$args;if($Platform -eq 'linux' -and $ApplyManifestEnvironment){$uid=(Invoke-ProcessAtomically 'id' @('-u') (Get-Location).Path (Join-Path $root ('streams-uid-'+$c.id)) $CommandTimeoutMinutes);$uidText=if(Test-Path $uid.stdout){(Get-Content -Raw $uid.stdout).Trim()}else{''};if($uid.completed -and $uidText -ne '0' -and (Get-Command sudo -ErrorAction SilentlyContinue)){$fileName='sudo';$childArgs=@('-n','env')+(@($childEnvironment.Keys|%{ "$_=$($childEnvironment[$_])" }))+'dotnet'+$args;$childEnvironment=@{}}};$p=Invoke-ProcessAtomically $fileName $childArgs (Get-Location).Path (Join-Path $root ('streams-'+$c.id)) $CommandTimeoutMinutes $childEnvironment;$files=@(Get-ChildItem -LiteralPath $slot -Filter '*.trx' -Recurse -ErrorAction SilentlyContinue|% FullName);$identity=Get-TrxIdentityResults $files $c.evidence.testName;$stdout=if(Test-Path $p.stdout){Get-Content -Raw $p.stdout}else{''};$result=Get-PlatformStatus $p $identity $stdout;$status=$result.status;$reason=$result.reason;if($status -eq 'BLOCKED'){$blocked=$true};if($status -eq 'FAIL'){$failed=$true};$rows += [ordered]@{id=$c.id;status=$status;evidence=$c.evidence;testIdentity=$c.evidence.testName;reason=$reason}}
    $a=[ordered]@{milestone=$m.milestone;slug=(Get-MilestoneSlug $m);platform=$Platform;sourceCommit=$SourceCommit;criteria=$rows};Ensure-OutputParent $Output;$a|ConvertTo-Json -Depth 20|Set-Content -LiteralPath $Output -Encoding utf8;Write-Output ("platform=$Platform output=$Output status=$(if($blocked){'BLOCKED'}elseif($failed){'FAIL'}else{'PASS_OR_PENDING'})");if($blocked -or $failed){exit 1}else{exit 0}
}
function Invoke-CiAggregation {
    $m=Read-Json $Manifest;Validate-Manifest $m;$l=Read-Json $LocalReport;$slug=Get-MilestoneSlug $m;if($l.milestone -ne $m.milestone){throw 'Local report milestone mismatch.'};$criteria=@($m.criteria|%{$_|ConvertTo-Json -Depth 20|ConvertFrom-Json});foreach($lc in $l.criteria){$c=$criteria|? id -eq $lc.id|Select-Object -First 1;if($null -ne $c){$c.status=$lc.status;if($null -ne $lc.result){$c|Add-Member result $lc.result -Force}}};$infra=@();$platformRows=@();foreach($path in $PlatformEvidence){$a=Read-Json $path;$p=$a.platform;$v=Read-PlatformArtifact $path $m $p $CiCommit;if(-not $v.valid){$infra+=$v.error;continue};$platformRows+=$a;foreach($pc in $a.criteria){$c=$criteria|? id -eq $pc.id|Select-Object -First 1;if($null -ne $c){$c.status=$pc.status;$c|Add-Member platformEvidence $pc -Force}}};$hard=@($criteria|?{$_.hardGate -and $_.status -eq 'FAIL'}|% id);$pending=@($criteria|? status -eq 'PENDING'|% id);$regression=[string]$l.milestoneRegressionStatus;if($infra.Count){$quality='BLOCKED'}elseif($hard.Count -or $regression -eq 'FAIL'){$quality='FAIL'}elseif($pending.Count){$quality='PROVISIONAL'}else{$quality='VERIFIED'};$score=Get-ScoreSummary $criteria $m.weights;$final=if($quality -eq 'VERIFIED'){$score.score}else{$null};$r=[ordered]@{milestone=$m.milestone;slug=$slug;milestoneTargetCommit=$m.targetCommit;ciRunId=$CiRunId;sourceCommit=$CiCommit;localStatus=$l.localStatus;repositoryHealth=$l.repositoryHealth;milestoneRegressionStatus=$regression;qualityStatus=$quality;finalQualityScore=$final;provisionalScore=$score.score;categoryScores=$score.categories;criteria=$criteria;requirementCoverage=[ordered]@{total=$criteria.Count;PASS=@($criteria|? status -eq PASS).Count;FAIL=@($criteria|? status -eq FAIL).Count;PENDING=@($criteria|? status -eq PENDING).Count;SKIP=@($criteria|? status -eq SKIP).Count};platformEvidence=$platformRows;pendingEvidence=$pending;hardGateFailures=$hard;infrastructureErrors=$infra;knownFailuresObserved=$l.knownFailuresObserved;newFailures=$l.newFailures;knownFailuresUnconfirmed=$l.knownFailuresUnconfirmed;efficiency=$l.efficiency};$dir=$OutputDirectory;New-Item -ItemType Directory -Force -Path $dir|Out-Null;$json=Join-Path $dir ($slug+'.ci.json');$md=Join-Path $dir ($slug+'.ci.md');$r|ConvertTo-Json -Depth 30|Set-Content $json -Encoding utf8;Write-Projection $md $r;Write-Output ("${quality}: $json");if($quality -in @('FAIL','BLOCKED')){exit 1}else{exit 0}
}
function Test-VerifiedEligibility($ci,$oldTarget,$generated,[string]$VerifiedRepositoryCommit) {
    return ($ci.qualityStatus -eq 'VERIFIED' -and $null -ne $ci.finalQualityScore -and @($ci.pendingEvidence).Count -eq 0 -and @($ci.hardGateFailures).Count -eq 0 -and @($ci.infrastructureErrors).Count -eq 0 -and $oldTarget -ne $ci.milestoneTargetCommit -and $generated.milestoneTargetCommit -eq $ci.milestoneTargetCommit -and $generated.verifiedRepositoryCommit -eq $VerifiedRepositoryCommit -and $generated.qualityStatus -eq 'VERIFIED')
}
function Merge-VerifiedIndexEntry($IndexObject,$Entry) {
    $items=@($IndexObject.milestones|?{$_.slug -ne $Entry.slug});$items += $Entry;$IndexObject.milestones=@($items|Sort-Object milestone,slug);return $IndexObject
}
function Invoke-FinalizeVerified {
    $r=Read-Json $CiReport;$active=Read-Json (Join-Path (Get-Location).Path 'agentic/_quality/active-milestone.json');$slug=$active.slug;if($r.sourceCommit -ne $ExpectedCommit -or $r.milestone -ne $active.milestone -or $r.slug -ne $slug){throw 'CI report identity/commit mismatch.'};if($r.qualityStatus -ne 'VERIFIED' -or $null -eq $r.finalQualityScore -or @($r.pendingEvidence).Count -ne 0 -or @($r.hardGateFailures).Count -ne 0 -or @($r.infrastructureErrors).Count -ne 0){Write-Output 'VERIFIED not eligible; no files generated.';exit 0};$verified=Join-Path $ReportsDirectory ($slug+'.verified.json');if(Test-Path $verified){$old=Read-Json $verified;if($old.milestoneTargetCommit -eq $r.milestoneTargetCommit){Write-Output 'VERIFIED already exists for target; idempotent skip.';exit 0}};$v=[ordered]@{milestone=$r.milestone;milestoneTargetCommit=$r.milestoneTargetCommit;verifiedRepositoryCommit=$ExpectedCommit;qualityStatus='VERIFIED';finalQualityScore=$r.finalQualityScore;categoryScores=$r.categoryScores;requirementCoverage=$r.requirementCoverage;platformEvidence=$r.platformEvidence;repositoryHealth=$r.repositoryHealth;milestoneRegressionStatus=$r.milestoneRegressionStatus;efficiency=$r.efficiency;ciRunId=$r.ciRunId;criteria=$r.criteria};New-Item -ItemType Directory -Force -Path $ReportsDirectory|Out-Null;$v|ConvertTo-Json -Depth 30|Set-Content $verified -Encoding utf8;Write-Projection (Join-Path $ReportsDirectory ($slug+'.verified.md')) $v;$idx=[ordered]@{schemaVersion='1.0';milestones=@()};if(Test-Path $Index){$idx=Read-Json $Index};$entries=@($idx.milestones|?{$_.slug -ne $slug});$entries += [ordered]@{milestone=$r.milestone;slug=$slug;workflowMode=$r.efficiency.workflowMode;packetCount=$r.efficiency.packetCount;quotaWindowPercent=$r.efficiency.quotaWindowPercent;qualityStatus='VERIFIED';finalQualityScore=$r.finalQualityScore;milestoneTargetCommit=$r.milestoneTargetCommit;verifiedRepositoryCommit=$ExpectedCommit;report=('agentic/_quality/reports/'+$slug+'.verified.json')};$idx.milestones=@($entries|Sort-Object milestone,slug);$idx|ConvertTo-Json -Depth 20|Set-Content $Index -Encoding utf8;Write-Output "VERIFIED generated: $verified";exit 0
}
function Test-Self {
    $base=[ordered]@{schemaVersion='1';milestone='SELF';targetCommit=('0'*40);baseReference='base';weights=[ordered]@{contractCoverage=30;negativeBoundaryCoverage=20;verificationMutationSafety=15;architectureSecurity=15;regressionEvidence=15;traceability=5};efficiency=@{};criteria=@()}
    foreach($x in @(@('a','contractCoverage','PASS',$false),@('b','contractCoverage','FAIL',$true),@('c','negativeBoundaryCoverage','PENDING',$false),@('d','traceability','PASS',$false))){$base.criteria += [pscustomobject]@{id=$x[0];category=$x[1];requirement='r';hardGate=$x[3];evidence=[pscustomobject]@{type='test'};status=$x[2]}}
    Validate-Manifest ([pscustomobject]$base); Assert-Quality ((@($base.criteria|? status -eq FAIL).Count)-eq 1) 'hard failure'; Assert-Quality ((@($base.criteria|? status -eq PENDING).Count)-gt 0) 'pending';$unknown=$base.criteria[0].category;$base.criteria[0].category='unknown';try{Validate-Manifest ([pscustomobject]$base);throw 'unknown category accepted'}catch{Assert-Quality ($_.Exception.Message -like '*Unknown category*') 'unknown category'};$base.criteria[0].category=$unknown
    try{$base.criteria += $base.criteria[0];Validate-Manifest ([pscustomobject]$base);throw 'duplicate accepted'}catch{Assert-Quality ($_.Exception.Message -like '*Duplicate criterion id*') 'duplicate'}
    $base.criteria=@($base.criteria|? id -ne 'a');$base.weights.contractCoverage=31;try{Validate-Manifest ([pscustomobject]$base);throw 'weights accepted'}catch{Assert-Quality ($_.Exception.Message -like '*sum to 100*') 'weights'}
    $tmp=Join-Path ([IO.Path]::GetTempPath()) ('bops-quality-self-'+[guid]::NewGuid().ToString('N'));New-Item -ItemType Directory -Path $tmp|Out-Null
    try{$valid=Join-Path $tmp 'valid.trx';Set-Content $valid '<TestRun><TestDefinitions><UnitTest id="1" name="T" /></TestDefinitions><Results><UnitTestResult testId="1" testName="T" outcome="Passed" /></Results><ResultSummary outcome="Completed" /></TestRun>';Assert-Quality ((Read-CompleteTrx $valid).valid) 'complete TRX';$bad=Join-Path $tmp 'bad.trx';Set-Content $bad '<TestRun><Results><UnitTestResult outcome="Passed" /></Results>';Assert-Quality (-not (Read-CompleteTrx $bad).valid) 'partial TRX';$reg=Join-Path $tmp 'known.json';Set-Content $reg '{"entries":[{"test":"T","classification":"known","evidence":"e","introducedBefore":"V1.3-F","isolatedExpectedToPass":true,"testProject":"p"}]}';Assert-Quality ((Read-KnownRegistry $reg).Count -eq 1) 'known registry';$pc=[pscustomobject]@{contractCoverage=30;negativeBoundaryCoverage=20;verificationMutationSafety=15;architectureSecurity=15;regressionEvidence=15;traceability=5};$pass=[pscustomobject]@{category='verificationMutationSafety';status='PASS'};$pend=[pscustomobject]@{category='verificationMutationSafety';status='PENDING'};$fail=[pscustomobject]@{category='verificationMutationSafety';status='FAIL'};Assert-Quality ((Get-ScoreSummary @($pass) $pc).score -eq 100) 'platform pass aggregation';Assert-Quality ((Get-ScoreSummary @($pass,$pend) $pc).score -eq 100) 'pending provisional score';Assert-Quality ((Get-ScoreSummary @($pass,$fail) $pc).categories.verificationMutationSafety.failed -eq 1) 'platform fail aggregation';$pa=Join-Path $tmp 'platform.json';Set-Content $pa '{"milestone":"V1.3-G","slug":"v1-3-g","platform":"windows","sourceCommit":"sha","criteria":[{"id":"x","status":"PASS"}]}';$mm=[pscustomobject]@{milestone='V1.3-G';criteria=@([pscustomobject]@{id='x';evidence=[pscustomobject]@{type='platform evidence';platform='windows'}})};Assert-Quality ((Read-PlatformArtifact $pa $mm 'windows' 'sha').valid) 'platform identity';Assert-Quality (-not (Read-PlatformArtifact $pa $mm 'linux' 'sha').valid) 'source/platform mismatch blocked';Assert-Quality ((Get-MilestoneSlug ([pscustomobject]@{milestone='V1.3-G'})) -eq 'v1-3-g') 'deterministic slug';$eff=[pscustomobject]@{workflowMode='manual-packet-orchestration';packetCount=7;quotaWindowPercent=9};Assert-Quality ($eff.packetCount -eq 7 -and $eff.quotaWindowPercent -eq 9) 'efficiency isolation'}finally{Remove-Item $tmp -Recurse -Force}
    $pathTmp=Join-Path ([IO.Path]::GetTempPath()) ('bops-quality-self-paths-'+[guid]::NewGuid().ToString('N'));New-Item -ItemType Directory -Path $pathTmp|Out-Null;Push-Location $pathTmp;$bare='quality.json';Ensure-OutputParent $bare;Pop-Location;Assert-Quality (-not (Split-Path -Parent $bare)) 'bare output path';$nested=Join-Path $pathTmp 'nested/quality.json';Ensure-OutputParent $nested;Assert-Quality (Test-Path (Split-Path -Parent $nested)) 'nested output path';$absolute=Join-Path ([IO.Path]::GetTempPath()) ('bops-quality-absolute-'+[guid]::NewGuid().ToString('N')+'/quality.json');Ensure-OutputParent $absolute;Assert-Quality (Test-Path (Split-Path -Parent $absolute)) 'absolute output path'
    $missing=Get-PlatformStatus ([pscustomobject]@{completed=$true;exitCode=1}) ([pscustomobject]@{results=@();errors=@()}) '';Assert-Quality ($missing.status -eq 'BLOCKED' -and $missing.reason -like '*identity*not found*') 'missing required platform identity is blocked';$skipped=Get-PlatformStatus ([pscustomobject]@{completed=$true;exitCode=0}) ([pscustomobject]@{results=@([pscustomobject]@{outcome='NotExecuted'});errors=@()}) '';Assert-Quality ($skipped.status -eq 'PENDING') 'explicit platform skip is pending';$passed=Get-PlatformStatus ([pscustomobject]@{completed=$true;exitCode=0}) ([pscustomobject]@{results=@([pscustomobject]@{outcome='Passed'});errors=@()}) '';Assert-Quality ($passed.status -eq 'PASS') 'platform pass is pass'
    $platformCriterion=[pscustomobject]@{evidence=[pscustomobject]@{platform='Linux'}};$platformPass=[pscustomobject]@{exists=$true;ran=$true;passed=$true;outcome='Passed'};$platformFail=[pscustomobject]@{exists=$true;ran=$true;passed=$false;outcome='Failed'};$platformSkip=[pscustomobject]@{exists=$true;ran=$false;passed=$false;outcome='NotExecuted'};Assert-Quality ((Get-PlatformCriterionStatus $platformCriterion 'Windows' $platformPass).status -eq 'PENDING') 'host mismatch is pending';Assert-Quality ((Get-PlatformCriterionStatus $platformCriterion 'Linux' $platformPass).status -eq 'PASS') 'matching host pass is pass';Assert-Quality ((Get-PlatformCriterionStatus $platformCriterion 'Linux' $platformFail).status -eq 'FAIL') 'matching host failure is fail';Assert-Quality ((Get-PlatformCriterionStatus $platformCriterion 'Linux' $platformSkip).status -eq 'PENDING') 'matching host skip is pending'
    New-Item -ItemType Directory -Force -Path $tmp | Out-Null;$emptyExpected=[pscustomobject]@{milestone='V1.3-H';criteria=@()};$oneExpected=[pscustomobject]@{milestone='V1.3-H';criteria=@([pscustomobject]@{id='linux-evidence';evidence=[pscustomobject]@{type='platform evidence';platform='Linux'}})};$twoExpected=[pscustomobject]@{milestone='V1.3-H';criteria=@([pscustomobject]@{id='linux-evidence';evidence=[pscustomobject]@{type='platform evidence';platform='Linux'}},[pscustomobject]@{id='linux-time';evidence=[pscustomobject]@{type='platform evidence';platform='Linux'}})};$emptyArtifact=Join-Path $tmp 'platform-empty.json';$oneArtifact=Join-Path $tmp 'platform-one.json';$unknownArtifact=Join-Path $tmp 'platform-unknown.json';$missingArtifact=Join-Path $tmp 'platform-missing.json';$duplicateArtifact=Join-Path $tmp 'platform-duplicate.json';$identityBase='{"milestone":"V1.3-H","slug":"v1-3-h","platform":"Linux","sourceCommit":"sha"}';Set-Content $emptyArtifact ($identityBase.Substring(0,$identityBase.Length-1)+',"criteria":[]}');Set-Content $oneArtifact ($identityBase.Substring(0,$identityBase.Length-1)+',"criteria":[{"id":"linux-evidence","status":"PASS"}]}');Set-Content $unknownArtifact ($identityBase.Substring(0,$identityBase.Length-1)+',"criteria":[{"id":"unknown","status":"PASS"}]}');Set-Content $missingArtifact ($identityBase.Substring(0,$identityBase.Length-1)+',"criteria":[]}');Set-Content $duplicateArtifact ($identityBase.Substring(0,$identityBase.Length-1)+',"criteria":[{"id":"linux-evidence","status":"PASS"},{"id":"linux-evidence","status":"PASS"}]}');Assert-Quality ((Read-PlatformArtifact $emptyArtifact $emptyExpected 'Linux' 'sha').valid) 'zero expected empty artifact is valid';Assert-Quality (-not (Read-PlatformArtifact $missingArtifact $oneExpected 'Linux' 'sha').valid) 'one expected empty artifact is blocked';Assert-Quality (-not (Read-PlatformArtifact $unknownArtifact $oneExpected 'Linux' 'sha').valid) 'unknown platform criterion is blocked';Assert-Quality (-not (Read-PlatformArtifact $oneArtifact $twoExpected 'Linux' 'sha').valid) 'missing platform criterion is blocked';Assert-Quality (-not (Read-PlatformArtifact $duplicateArtifact $oneExpected 'Linux' 'sha').valid) 'duplicate platform criterion is blocked'
    $envTest=Invoke-ProcessAtomically 'pwsh' @('-NoProfile','-Command','[Console]::Write($env:BOPS_QUALITY_SELF)') $pathTmp (Join-Path $pathTmp 'env') 1 @{BOPS_QUALITY_SELF='child-only'};Assert-Quality ($envTest.completed -and (Get-Content -Raw $envTest.stdout).Trim() -eq 'child-only' -and $null -eq $env:BOPS_QUALITY_SELF) 'environment is child-only'
    $ci=[pscustomobject]@{qualityStatus='VERIFIED';finalQualityScore=100;pendingEvidence=@();hardGateFailures=@();infrastructureErrors=@();milestoneTargetCommit='target'};$generated=[pscustomobject]@{milestoneTargetCommit='target';verifiedRepositoryCommit='verified';qualityStatus='VERIFIED'};Assert-Quality (Test-VerifiedEligibility $ci 'old-target' $generated 'verified') 'target and verified repository commits are distinct';$hardCriterion=[pscustomobject]@{hardGate=$true;status='FAIL'};$hardQuality=if(@($hardCriterion|?{$_.hardGate -and $_.status -eq 'FAIL'}).Count){'FAIL'}else{'VERIFIED'};Assert-Quality ($hardQuality -eq 'FAIL') 'hard failure overrides score';$scoreBefore=(Get-ScoreSummary @($pass) $pc).score;$eff=[pscustomobject]@{workflowMode='manual-packet-orchestration';packetCount=7;quotaWindowPercent=9};Assert-Quality ($eff.packetCount -eq 7 -and $eff.quotaWindowPercent -eq 9 -and $scoreBefore -eq (Get-ScoreSummary @($pass) $pc).score) 'efficiency isolation';$idx=[ordered]@{milestones=@([ordered]@{slug='v1-3-g';milestoneTargetCommit='old'})};$entry=[ordered]@{slug='v1-3-g';milestoneTargetCommit='target'};$idx=Merge-VerifiedIndexEntry $idx $entry;$idx=Merge-VerifiedIndexEntry $idx $entry;Assert-Quality (@($idx.milestones|? slug -eq 'v1-3-g').Count -eq 1) 'verified index is idempotent'
    Remove-Item -LiteralPath $pathTmp -Recurse -Force -ErrorAction SilentlyContinue;Remove-Item -LiteralPath $absolute -Recurse -Force -ErrorAction SilentlyContinue
    Write-Output 'SELF PASS: atomic process/TRX validity, failure-vs-blocked semantics, pending provisionality, schema guards, output paths, child environment, finalizer eligibility and efficiency isolation'
}
if($TestSelf){Test-Self;exit 0}
if($CollectPlatformEvidence){Invoke-PlatformCollection;exit 0}
if($AggregateCiEvidence){Invoke-CiAggregation;exit 0}
if($FinalizeVerified){Invoke-FinalizeVerified;exit 0}

$repo=(Get-Location).Path;$m=Read-Json $Manifest;Validate-Manifest $m;$slug=Get-MilestoneSlug $m;$registry=Read-KnownRegistry (Join-Path $repo $KnownFailures);$reportDir=Join-Path $repo 'agentic/_quality/reports';New-Item -ItemType Directory -Force -Path $reportDir|Out-Null;$criteria=@($m.criteria|%{$_|ConvertTo-Json -Depth 20|ConvertFrom-Json});$runDir=if($EvidenceDirectory){(Resolve-Path -LiteralPath $EvidenceDirectory).Path}else{New-RunDirectory $repo $m.milestone};$infra=@();$hard=@();$pending=@();$build=$null;$test=$null;$trxFiles=@()
if($EvidenceDirectory){$buildText=Get-Content -Raw (Join-Path $runDir 'streams/build/stdout.txt');$buildOk=($buildText -match '(?im)(Warnings?|Avvisi):\s*0' -and $buildText -match '(?im)(Errors?|Errori):\s*0');$build=[pscustomobject]@{completed=$true;exitCode=if($buildOk){0}else{1};command='reused build evidence'};$trxFiles=@(Get-ChildItem -LiteralPath (Join-Path $runDir 'trx') -Filter '*.trx' -Recurse|% FullName);if($trxFiles.Count -eq 0){$infra+='Expected TRX files were not produced.'}}
elseif($SmokeTest -or $RunTests){$build=Invoke-ProcessAtomically 'dotnet' @('build','bOps.slnx','--configuration','Release','--nologo') $repo (Join-Path $runDir 'streams/build') $CommandTimeoutMinutes;if(-not $build.completed){$infra+=$build.infrastructureError};if($SmokeTest){$testArgs=@('test','tests/bOps.Packages.Scheduler.Core.Tests/bOps.Packages.Scheduler.Core.Tests.csproj','--configuration','Release','--no-build','--logger','trx','--results-directory',(Join-Path $runDir 'trx/smoke'),'--nologo')}else{$testArgs=@('test','bOps.slnx','-c','Release','--no-build','--filter','Category!=LiveModel','--logger','trx','--results-directory',(Join-Path $runDir 'trx/full'),'--nologo')};$test=Invoke-ProcessAtomically 'dotnet' $testArgs $repo (Join-Path $runDir 'streams/test') $CommandTimeoutMinutes;if(-not $test.completed){$infra+=$test.infrastructureError};if($test.completed){$trxFiles=@(Get-ChildItem -LiteralPath (Join-Path $runDir 'trx') -Filter '*.trx' -Recurse|% FullName);if($trxFiles.Count -eq 0){$infra+='Expected TRX files were not produced.'}}}
$combined=Get-CombinedTests $trxFiles; if($combined.errors.Count){$infra+=$combined.errors};if($EvidenceDirectory){$test=[pscustomobject]@{completed=$true;exitCode=if($combined.failed -gt 0){1}else{0};command='reused full-suite evidence'}}
if($VerifyKnownFailures -and -not $EvidenceDirectory){$infra+='Known-failure verification requires -EvidenceDirectory or a completed -RunTests invocation.'}
$knownObserved=@();$newFailures=@();$knownUnconfirmed=@();$knownVerificationErrors=@();$fullFailed=@($combined.results|?{$_.outcome -in @('Failed','Error')});foreach($failure in $fullFailed){$entry=@($registry|?{$_.test -eq [string]$failure.testName}|Select-Object -First 1);if(-not $entry){$newFailures += [ordered]@{test=[string]$failure.testName;classification='NEW_FAILURE';fullSuiteResult=[string]$failure.outcome};continue};$verification=[ordered]@{test=$entry.test;classification='KNOWN_FAILURE_UNCONFIRMED';sourceEvidence=$entry.evidence;fullSuiteResult=[string]$failure.outcome;isolatedVerificationResult='NOT_RUN'};if($VerifyKnownFailures -and $entry.isolatedExpectedToPass){$slot=Join-Path $runDir ('trx/known/'+([guid]::NewGuid().ToString('N')));$isolated=Invoke-ProcessAtomically 'dotnet' @('test',(Join-Path $repo $entry.testProject),'--configuration','Release','--no-build','--filter',('FullyQualifiedName='+$entry.test),'--logger','trx','--results-directory',$slot,'--nologo') $repo (Join-Path $runDir 'streams/known') $CommandTimeoutMinutes;$isolatedFiles=@(Get-ChildItem -LiteralPath $slot -Filter '*.trx' -Recurse -ErrorAction SilentlyContinue|% FullName);$isolatedCombined=Get-CombinedTests $isolatedFiles;if(-not $isolated.completed -or $isolatedCombined.errors.Count -or $isolatedFiles.Count -eq 0){$knownVerificationErrors += "Known-failure verification infrastructure error: $($entry.test)";$verification.isolatedVerificationResult='BLOCKED'}elseif(@($isolatedCombined.results|?{$_.testName -eq $entry.test -and $_.outcome -eq 'Passed'}).Count -eq 1 -and $isolated.exitCode -eq 0){$verification.classification='KNOWN_FAILURE_CONFIRMED';$verification.isolatedVerificationResult='PASS'}else{$verification.isolatedVerificationResult=if(@($isolatedCombined.results|?{$_.testName -eq $entry.test -and $_.outcome -in @('NotExecuted','Skipped')}).Count){'SKIP'}else{'FAIL'}}}else{$knownVerificationErrors += "Known-failure verification not run: $($entry.test)"};if($verification.classification -eq 'KNOWN_FAILURE_UNCONFIRMED'){$knownUnconfirmed += $verification}else{$knownObserved += $verification}}
$infra += $knownVerificationErrors
$milestoneRegressionStatus=if($infra.Count){'BLOCKED'}elseif($newFailures.Count -or $knownUnconfirmed.Count){'FAIL'}else{'PASS'};$repositoryHealth=if($infra.Count){'BLOCKED'}elseif($combined.failed -eq 0){'HEALTHY'}elseif($knownObserved.Count -eq $combined.failed){'DEGRADED_KNOWN_FAILURES'}else{'FAIL'}
function Find-Test($c){$name=[string]$c.evidence.testName;if(-not $combined.results){return [pscustomobject]@{exists=$false;ran=$false;passed=$false;outcome='NOT_FOUND'}};$r=@($combined.results|?{$_.testName -like "*$name*"});if(-not $r.Count){return [pscustomobject]@{exists=$false;ran=$false;passed=$false;outcome='NOT_FOUND'}};$ran=@($r|? outcome -notin @('NotExecuted','Skipped'));[pscustomobject]@{exists=$true;ran=($ran.Count-gt 0);passed=($ran.Count-gt 0 -and @($ran|? outcome -ne Passed).Count -eq 0);outcome=([string]$r[0].outcome)}}
foreach($c in $criteria){$e=[string]$c.evidence.type;if($e -eq 'platform evidence'){$r=Find-Test $c;$platformResult=Get-PlatformCriterionStatus $c (Get-LocalQualityPlatform) $r;$c.status=$platformResult.status;$c|Add-Member result ([pscustomobject]@{exists=$r.exists;ran=$r.ran;passed=($platformResult.status -eq 'PASS');outcome=$platformResult.outcome}) -Force}elseif($e -in @('exact automated test','architecture test')){$r=Find-Test $c;$c|Add-Member result $r -Force;if($r.passed){$c.status='PASS'}elseif($r.exists -and $r.ran){$c.status='FAIL'}else{$c.status='PENDING'}}elseif($c.id -eq 'regression-release-build'){$c.status=if($build -and $build.completed -and $build.exitCode -eq 0){'PASS'}elseif($build -and $build.completed){'FAIL'}else{'PENDING'}}elseif($c.id -eq 'regression-full-non-live'){$c.status=if($milestoneRegressionStatus -eq 'PASS'){'PASS'}elseif($milestoneRegressionStatus -eq 'FAIL'){'FAIL'}else{'PENDING'}}elseif($c.id -eq 'regression-architecture-gate'){$c.status=if($test -and $test.completed -and @($criteria|?{$_.category -eq 'architectureSecurity' -and $_.status -eq 'FAIL'}).Count -eq 0){'PASS'}else{'PENDING'}}elseif($c.id -eq 'regression-service-gate'){$c.status=if($test -and $test.completed -and @($criteria|?{$_.evidence.testProject -like '*Service*' -and $_.evidence.type -eq 'exact automated test' -and $_.status -eq 'FAIL'}).Count -eq 0){'PASS'}else{'PENDING'}}elseif($c.id -eq 'regression-scheduler-gate'){$c.status=if($test -and $test.completed -and @($criteria|?{$_.evidence.testProject -like '*Scheduler*' -and $_.evidence.type -eq 'exact automated test' -and $_.status -eq 'FAIL'}).Count -eq 0){'PASS'}else{'PENDING'}}}
$summary=[ordered]@{total=$criteria.Count;PASS=(@($criteria|? status -eq PASS).Count);FAIL=(@($criteria|? status -eq FAIL).Count);PENDING=(@($criteria|? status -eq PENDING).Count);SKIP=(@($criteria|? status -eq SKIP).Count)};$cats=[ordered]@{};$num=0;$den=0;foreach($cat in $Categories){$rows=@($criteria|? category -eq $cat);$p=@($rows|? status -eq PASS).Count;$f=@($rows|? status -eq FAIL).Count;$q=@($rows|? status -eq PENDING).Count;$s=@($rows|? status -eq SKIP).Count;$score=if($p+$f){[math]::Round(100*$p/($p+$f),2)}else{$null};$cats[$cat]=[ordered]@{passed=$p;failed=$f;pending=$q;skipped=$s;score=$score;weight=[double]$m.weights.$cat};if($null-ne$score){$num+=$score*[double]$m.weights.$cat;$den+=[double]$m.weights.$cat}}
$hard+=@($criteria|?{$_.hardGate -and $_.status -eq 'FAIL'}|% id);$pending+=@($criteria|?{$_.status -eq 'PENDING'}|% id);$local=if($infra.Count){'BLOCKED'}elseif($hard.Count){'FAIL'}else{'PASS'};$pendingRequired=$pending.Count -gt 0;$provisional=if($den){[math]::Round($num/$den,2)}else{$null};$final=if(-not $pendingRequired -and $local -eq 'PASS'){$provisional}else{$null};$quality=if($local -eq 'BLOCKED'){'BLOCKED'}elseif($local -eq 'FAIL'){'FAIL'}elseif($pendingRequired){'PROVISIONAL'}elseif($final -ge 95){'VERIFIED'}elseif($final -ge 90){'ACCEPTABLE'}else{'NOT_READY'}
$buildSummary=if($build){[ordered]@{completed=$build.completed;exitCode=$build.exitCode;timedOut=$build.timedOut;command=$build.command}}else{$null};$testSummary=if($test){[ordered]@{completed=$test.completed;exitCode=$test.exitCode;timedOut=$test.timedOut;command=$test.command}}else{$null};$relativeTrx=@($trxFiles|%{ $_.Substring($repo.Length).TrimStart('\','/') -replace '\\','/' });$exec=[ordered]@{build=$buildSummary;fullSuite=$testSummary;trxFiles=$relativeTrx;counts=[ordered]@{total=$combined.total;passed=$combined.passed;failed=$combined.failed;skipped=$combined.skipped};evidenceDirectory='artifacts/quality/<milestone>'};$report=[ordered]@{milestone=$m.milestone;targetCommit=$m.targetCommit;baseReference=$m.baseReference;localStatus=$local;qualityStatus=$quality;repositoryHealth=$repositoryHealth;milestoneRegressionStatus=$milestoneRegressionStatus;infrastructureErrors=$infra;hardGateFailures=$hard;pendingEvidence=$pending;knownFailuresObserved=$knownObserved;newFailures=$newFailures;knownFailuresUnconfirmed=$knownUnconfirmed;criteria=$criteria;requirementCoverage=$summary;categoryScores=$cats;provisionalScore=$provisional;finalQualityScore=$final;testExecution=$exec;platformEvidencePending=@($criteria|?{$_.status -eq 'PENDING' -and $_.evidence.type -eq 'platform evidence'}|% id);efficiency=$m.efficiency}
$json=Join-Path $reportDir ($slug+'.local.json');$md=Join-Path $reportDir ($slug+'.local.md');$report|ConvertTo-Json -Depth 30|Set-Content $json -Encoding utf8;$lines=@("# $($m.milestone) Quality Baseline",'',"Target commit: $($m.targetCommit)","Status: $quality","Local status: $local",'', '## Category scores','', '| category | passed | failed | pending | score | weight |','|---|---:|---:|---:|---:|---:|');foreach($cat in $Categories){$v=$cats[$cat];$lines += "| $cat | $($v.passed) | $($v.failed) | $($v.pending) | $($v.score) | $($v.weight) |"};$lines+=@('', '## Requirement coverage',"total / pass / fail / pending / skip: $($summary.total) / $($summary.PASS) / $($summary.FAIL) / $($summary.PENDING) / $($summary.SKIP)",'', '## Regression',"build exit: $($build.exitCode)","full tests exit: $($test.exitCode)","TRX counts: $($combined.total) total / $($combined.passed) / $($combined.failed) / $($combined.skipped) skipped", "platform evidence pending: $([string]::Join(', ', $report.platformEvidencePending))",'', '## Efficiency',"workflow: $($m.efficiency.workflowMode)","packet count: $($m.efficiency.packetCount)","quota %: $($m.efficiency.quotaWindowPercent)",'', '## Score',"provisional score: $provisional","final score: $final",'', '## Outstanding evidence');$lines+=@($pending|%{"- $_"});$lines|%{$_.TrimEnd()}|Set-Content $md -Encoding utf8;Write-Output ("${quality}: local=$local criteria=$($summary.total) PASS=$($summary.PASS) FAIL=$($summary.FAIL) PENDING=$($summary.PENDING) SKIP=$($summary.SKIP) tests=$($combined.total)/$($combined.passed)/$($combined.failed)/$($combined.skipped)");if($local -ne 'PASS' -or ($pendingRequired -and -not $AllowPendingExternal)){exit 1}else{exit 0}










