[CmdletBinding()]
param(
    [string]$Manifest = 'agentic/_quality/manifests/v1.3-g.json',
    [switch]$RunTests,
    [switch]$SmokeTest,
    [switch]$AllowPendingExternal,
    [switch]$TestSelf,
    [string]$EvidenceDirectory,
    [string]$KnownFailures = 'agentic/_quality/known-failures.json',
    [switch]$VerifyKnownFailures,
    [ValidateRange(1,120)][int]$CommandTimeoutMinutes = 30
)
$ErrorActionPreference = 'Stop'
$Categories = @('contractCoverage','negativeBoundaryCoverage','verificationMutationSafety','architectureSecurity','regressionEvidence','traceability')
$Allowed = @('PASS','FAIL','PENDING','SKIP')

function Assert-Quality([bool]$Condition,[string]$Message) { if (-not $Condition) { throw "Self-test failed: $Message" } }
function Read-Json([string]$Path) { Get-Content -Raw -LiteralPath $Path | ConvertFrom-Json }
function Validate-Manifest($m) {
    if (-not $m.criteria) { throw 'Manifest has no criteria.' }
    $ids = @{}
    foreach ($c in $m.criteria) {
        if ($ids.ContainsKey($c.id)) { throw "Duplicate criterion id: $($c.id)" }; $ids[$c.id] = $true
        if ($Categories -notcontains $c.category) { throw "Unknown category: $($c.category)" }
        if ($Allowed -notcontains $c.status) { throw "Invalid status: $($c.status)" }
        foreach ($p in 'id','category','requirement','hardGate','evidence','status') { if ($null -eq $c.$p) { throw "Missing criterion property $p ($($c.id))." } }
    }
    $sum = 0; foreach ($cat in $Categories) { $sum += [double]$m.weights.$cat }
    if ($sum -ne 100) { throw "Category weights must sum to 100 (actual $sum)." }
}
function New-RunDirectory([string]$Root,[string]$Milestone) {
    $safe = $Milestone.ToLowerInvariant().Replace('.','-'); $dir = Join-Path $Root (Join-Path 'artifacts/quality' $safe)
    if (Test-Path $dir) { Remove-Item -LiteralPath $dir -Recurse -Force }
    New-Item -ItemType Directory -Force -Path (Join-Path $dir 'trx') | Out-Null
    New-Item -ItemType Directory -Force -Path (Join-Path $dir 'streams') | Out-Null
    return $dir
}
function Invoke-ProcessAtomically([string]$FileName,[string[]]$CommandArguments,[string]$WorkingDirectory,[string]$OutputDirectory,[int]$TimeoutMinutes) {
    New-Item -ItemType Directory -Force -Path $OutputDirectory | Out-Null
    $stdoutPath = Join-Path $OutputDirectory 'stdout.txt'; $stderrPath = Join-Path $OutputDirectory 'stderr.txt'
    $psi = [Diagnostics.ProcessStartInfo]::new(); $psi.FileName=$FileName; $psi.WorkingDirectory=$WorkingDirectory; $psi.UseShellExecute=$false; $psi.CreateNoWindow=$true; $psi.RedirectStandardOutput=$true; $psi.RedirectStandardError=$true
    foreach ($arg in $CommandArguments) { [void]$psi.ArgumentList.Add($arg) }
    $p = [Diagnostics.Process]::new(); $p.StartInfo=$psi; $started=$false; $timedOut=$false; $infra=$null; $exit=$null; $out=''; $err=''
    try {
        $started=$p.Start(); if (-not $started) { throw 'Process.Start returned false.' }
        $outTask=$p.StandardOutput.ReadToEndAsync(); $errTask=$p.StandardError.ReadToEndAsync()
        if (-not $p.WaitForExit($TimeoutMinutes*60*1000)) { $timedOut=$true; $infra="Process timed out after $TimeoutMinutes minute(s): $FileName $($CommandArguments -join ' ')"; try { $p.Kill($true) } catch { }; $p.WaitForExit() }
        $out=$outTask.GetAwaiter().GetResult(); $err=$errTask.GetAwaiter().GetResult(); $exit=$p.ExitCode
    } catch { $infra="Process infrastructure failure: $($_.Exception.Message)" } finally { $p.Dispose() }
    Set-Content -LiteralPath $stdoutPath -Value $out -Encoding utf8; Set-Content -LiteralPath $stderrPath -Value $err -Encoding utf8
    [pscustomobject]@{ completed=($started -and -not $timedOut -and $null -ne $exit); exitCode=$exit; timedOut=$timedOut; infrastructureError=$infra; stdout=$stdoutPath; stderr=$stderrPath; command=("$FileName $($CommandArguments -join ' ')") }
}
function Read-CompleteTrx([string]$Path) {
    try { [xml]$x=Get-Content -Raw -LiteralPath $Path } catch { return [pscustomobject]@{valid=$false;error="Malformed TRX: $Path"} }
    $results=@($x.TestRun.Results.UnitTestResult)
    if (-not $x.TestRun -or -not $x.TestRun.Results -or $results.Count -eq 0 -or -not $x.TestRun.TestDefinitions -or -not $x.TestRun.ResultSummary) { return [pscustomobject]@{valid=$false;error="Incomplete TRX: $Path"} }
    [pscustomobject]@{valid=$true;path=$Path;results=$results}
}
function Get-CombinedTests($TrxFiles) {
    $all=@(); $errors=@(); foreach($f in $TrxFiles){$t=Read-CompleteTrx $f;if($t.valid){$all += $t.results}else{$errors += $t.error}}
    [pscustomobject]@{results=$all;errors=$errors;total=$all.Count;passed=@($all|? outcome -eq Passed).Count;failed=@($all|?{$_.outcome -in @('Failed','Error')}).Count;skipped=@($all|?{$_.outcome -in @('NotExecuted','Skipped')}).Count}
}
function Read-KnownRegistry([string]$Path) {
    $r=Read-Json $Path; if(-not $r.entries){throw 'Known-failure registry has no entries.'};$ids=@{};foreach($e in $r.entries){foreach($p in 'test','classification','evidence','introducedBefore','isolatedExpectedToPass','testProject'){if($null -eq $e.$p){throw "Known-failure entry missing $p."}};if($ids.ContainsKey($e.test)){throw "Duplicate known-failure test: $($e.test)"};$ids[$e.test]=$true};return @($r.entries)
}
function Test-Self {
    $base=[ordered]@{schemaVersion='1';milestone='SELF';targetCommit=('0'*40);baseReference='base';weights=[ordered]@{contractCoverage=30;negativeBoundaryCoverage=20;verificationMutationSafety=15;architectureSecurity=15;regressionEvidence=15;traceability=5};efficiency=@{};criteria=@()}
    foreach($x in @(@('a','contractCoverage','PASS',$false),@('b','contractCoverage','FAIL',$true),@('c','negativeBoundaryCoverage','PENDING',$false),@('d','traceability','PASS',$false))){$base.criteria += [pscustomobject]@{id=$x[0];category=$x[1];requirement='r';hardGate=$x[3];evidence=[pscustomobject]@{type='test'};status=$x[2]}}
    Validate-Manifest ([pscustomobject]$base); Assert-Quality ((@($base.criteria|? status -eq FAIL).Count)-eq 1) 'hard failure'; Assert-Quality ((@($base.criteria|? status -eq PENDING).Count)-gt 0) 'pending'
    try{$base.criteria += $base.criteria[0];Validate-Manifest ([pscustomobject]$base);throw 'duplicate accepted'}catch{Assert-Quality ($_.Exception.Message -like '*Duplicate criterion id*') 'duplicate'}
    $base.criteria=@($base.criteria|? id -ne 'a');$base.weights.contractCoverage=31;try{Validate-Manifest ([pscustomobject]$base);throw 'weights accepted'}catch{Assert-Quality ($_.Exception.Message -like '*sum to 100*') 'weights'}
    $tmp=Join-Path ([IO.Path]::GetTempPath()) ('bops-quality-self-'+[guid]::NewGuid().ToString('N'));New-Item -ItemType Directory -Path $tmp|Out-Null
    try{$valid=Join-Path $tmp 'valid.trx';Set-Content $valid '<TestRun><TestDefinitions><UnitTest id="1" name="T" /></TestDefinitions><Results><UnitTestResult testId="1" testName="T" outcome="Passed" /></Results><ResultSummary outcome="Completed" /></TestRun>';Assert-Quality ((Read-CompleteTrx $valid).valid) 'complete TRX';$bad=Join-Path $tmp 'bad.trx';Set-Content $bad '<TestRun><Results><UnitTestResult outcome="Passed" /></Results>';Assert-Quality (-not (Read-CompleteTrx $bad).valid) 'partial TRX';$reg=Join-Path $tmp 'known.json';Set-Content $reg '{"entries":[{"test":"T","classification":"known","evidence":"e","introducedBefore":"V1.3-F","isolatedExpectedToPass":true,"testProject":"p"}]}';Assert-Quality ((Read-KnownRegistry $reg).Count -eq 1) 'known registry'}finally{Remove-Item $tmp -Recurse -Force}
    Write-Output 'SELF PASS: atomic process/TRX validity, failure-vs-blocked semantics, pending provisionality, schema guards and efficiency isolation'
}
if($TestSelf){Test-Self;exit 0}

$repo=(Get-Location).Path;$m=Read-Json $Manifest;Validate-Manifest $m;$registry=Read-KnownRegistry (Join-Path $repo $KnownFailures);$reportDir=Join-Path $repo 'agentic/_quality/reports';New-Item -ItemType Directory -Force -Path $reportDir|Out-Null;$criteria=@($m.criteria|%{$_|ConvertTo-Json -Depth 20|ConvertFrom-Json});$runDir=if($EvidenceDirectory){(Resolve-Path -LiteralPath $EvidenceDirectory).Path}else{New-RunDirectory $repo $m.milestone};$infra=@();$hard=@();$pending=@();$build=$null;$test=$null;$trxFiles=@()
if($EvidenceDirectory){$buildText=Get-Content -Raw (Join-Path $runDir 'streams/build/stdout.txt');$buildOk=($buildText -match '(?im)(Warnings?|Avvisi):\s*0' -and $buildText -match '(?im)(Errors?|Errori):\s*0');$build=[pscustomobject]@{completed=$true;exitCode=if($buildOk){0}else{1};command='reused build evidence'};$trxFiles=@(Get-ChildItem -LiteralPath (Join-Path $runDir 'trx') -Filter '*.trx' -Recurse|% FullName);if($trxFiles.Count -eq 0){$infra+='Expected TRX files were not produced.'}}
elseif($SmokeTest -or $RunTests){$build=Invoke-ProcessAtomically 'dotnet' @('build','bOps.slnx','--configuration','Release','--nologo') $repo (Join-Path $runDir 'streams/build') $CommandTimeoutMinutes;if(-not $build.completed){$infra+=$build.infrastructureError};if($SmokeTest){$testArgs=@('test','tests/bOps.Packages.Scheduler.Core.Tests/bOps.Packages.Scheduler.Core.Tests.csproj','--configuration','Release','--no-build','--logger','trx','--results-directory',(Join-Path $runDir 'trx/smoke'),'--nologo')}else{$testArgs=@('test','bOps.slnx','-c','Release','--no-build','--filter','Category!=LiveModel','--logger','trx','--results-directory',(Join-Path $runDir 'trx/full'),'--nologo')};$test=Invoke-ProcessAtomically 'dotnet' $testArgs $repo (Join-Path $runDir 'streams/test') $CommandTimeoutMinutes;if(-not $test.completed){$infra+=$test.infrastructureError};if($test.completed){$trxFiles=@(Get-ChildItem -LiteralPath (Join-Path $runDir 'trx') -Filter '*.trx' -Recurse|% FullName);if($trxFiles.Count -eq 0){$infra+='Expected TRX files were not produced.'}}}
$combined=Get-CombinedTests $trxFiles; if($combined.errors.Count){$infra+=$combined.errors};if($EvidenceDirectory){$test=[pscustomobject]@{completed=$true;exitCode=if($combined.failed -gt 0){1}else{0};command='reused full-suite evidence'}}
if($VerifyKnownFailures -and -not $EvidenceDirectory){$infra+='Known-failure verification requires -EvidenceDirectory or a completed -RunTests invocation.'}
$knownObserved=@();$newFailures=@();$knownUnconfirmed=@();$knownVerificationErrors=@();$fullFailed=@($combined.results|?{$_.outcome -in @('Failed','Error')});foreach($failure in $fullFailed){$entry=@($registry|?{$_.test -eq [string]$failure.testName}|Select-Object -First 1);if(-not $entry){$newFailures += [ordered]@{test=[string]$failure.testName;classification='NEW_FAILURE';fullSuiteResult=[string]$failure.outcome};continue};$verification=[ordered]@{test=$entry.test;classification='KNOWN_FAILURE_UNCONFIRMED';sourceEvidence=$entry.evidence;fullSuiteResult=[string]$failure.outcome;isolatedVerificationResult='NOT_RUN'};if($VerifyKnownFailures -and $entry.isolatedExpectedToPass){$slot=Join-Path $runDir ('trx/known/'+([guid]::NewGuid().ToString('N')));$isolated=Invoke-ProcessAtomically 'dotnet' @('test',(Join-Path $repo $entry.testProject),'--configuration','Release','--no-build','--filter',('FullyQualifiedName='+$entry.test),'--logger','trx','--results-directory',$slot,'--nologo') $repo (Join-Path $runDir 'streams/known') $CommandTimeoutMinutes;$isolatedFiles=@(Get-ChildItem -LiteralPath $slot -Filter '*.trx' -Recurse -ErrorAction SilentlyContinue|% FullName);$isolatedCombined=Get-CombinedTests $isolatedFiles;if(-not $isolated.completed -or $isolatedCombined.errors.Count -or $isolatedFiles.Count -eq 0){$knownVerificationErrors += "Known-failure verification infrastructure error: $($entry.test)";$verification.isolatedVerificationResult='BLOCKED'}elseif(@($isolatedCombined.results|?{$_.testName -eq $entry.test -and $_.outcome -eq 'Passed'}).Count -eq 1 -and $isolated.exitCode -eq 0){$verification.classification='KNOWN_FAILURE_CONFIRMED';$verification.isolatedVerificationResult='PASS'}else{$verification.isolatedVerificationResult=if(@($isolatedCombined.results|?{$_.testName -eq $entry.test -and $_.outcome -in @('NotExecuted','Skipped')}).Count){'SKIP'}else{'FAIL'}}}else{$knownVerificationErrors += "Known-failure verification not run: $($entry.test)"};if($verification.classification -eq 'KNOWN_FAILURE_UNCONFIRMED'){$knownUnconfirmed += $verification}else{$knownObserved += $verification}}
$infra += $knownVerificationErrors
$milestoneRegressionStatus=if($infra.Count){'BLOCKED'}elseif($newFailures.Count -or $knownUnconfirmed.Count){'FAIL'}else{'PASS'};$repositoryHealth=if($infra.Count){'BLOCKED'}elseif($combined.failed -eq 0){'HEALTHY'}elseif($knownObserved.Count -eq $combined.failed){'DEGRADED_KNOWN_FAILURES'}else{'FAIL'}
function Find-Test($c){$name=[string]$c.evidence.testName;if(-not $combined.results){return [pscustomobject]@{exists=$false;ran=$false;passed=$false;outcome='NOT_FOUND'}};$r=@($combined.results|?{$_.testName -like "*$name*"});if(-not $r.Count){return [pscustomobject]@{exists=$false;ran=$false;passed=$false;outcome='NOT_FOUND'}};$ran=@($r|? outcome -notin @('NotExecuted','Skipped'));[pscustomobject]@{exists=$true;ran=($ran.Count-gt 0);passed=($ran.Count-gt 0 -and @($ran|? outcome -ne Passed).Count -eq 0);outcome=([string]$r[0].outcome)}}
foreach($c in $criteria){$e=[string]$c.evidence.type;if($e -in @('exact automated test','architecture test','platform evidence')){$r=Find-Test $c;$c|Add-Member result $r -Force;if($r.passed){$c.status='PASS'}elseif($r.exists -and $r.ran){$c.status='FAIL'}else{$c.status='PENDING'}}elseif($c.id -eq 'regression-release-build'){$c.status=if($build -and $build.completed -and $build.exitCode -eq 0){'PASS'}elseif($build -and $build.completed){'FAIL'}else{'PENDING'}}elseif($c.id -eq 'regression-full-non-live'){$c.status=if($milestoneRegressionStatus -eq 'PASS'){'PASS'}elseif($milestoneRegressionStatus -eq 'FAIL'){'FAIL'}else{'PENDING'}}elseif($c.id -eq 'regression-architecture-gate'){$c.status=if($test -and $test.completed -and @($criteria|?{$_.category -eq 'architectureSecurity' -and $_.status -eq 'FAIL'}).Count -eq 0){'PASS'}else{'PENDING'}}elseif($c.id -eq 'regression-service-gate'){$c.status=if($test -and $test.completed -and @($criteria|?{$_.evidence.testProject -like '*Service*' -and $_.evidence.type -eq 'exact automated test' -and $_.status -eq 'FAIL'}).Count -eq 0){'PASS'}else{'PENDING'}}elseif($c.id -eq 'regression-scheduler-gate'){$c.status=if($test -and $test.completed -and @($criteria|?{$_.evidence.testProject -like '*Scheduler*' -and $_.evidence.type -eq 'exact automated test' -and $_.status -eq 'FAIL'}).Count -eq 0){'PASS'}else{'PENDING'}}}
$summary=[ordered]@{total=$criteria.Count;PASS=(@($criteria|? status -eq PASS).Count);FAIL=(@($criteria|? status -eq FAIL).Count);PENDING=(@($criteria|? status -eq PENDING).Count);SKIP=(@($criteria|? status -eq SKIP).Count)};$cats=[ordered]@{};$num=0;$den=0;foreach($cat in $Categories){$rows=@($criteria|? category -eq $cat);$p=@($rows|? status -eq PASS).Count;$f=@($rows|? status -eq FAIL).Count;$q=@($rows|? status -eq PENDING).Count;$s=@($rows|? status -eq SKIP).Count;$score=if($p+$f){[math]::Round(100*$p/($p+$f),2)}else{$null};$cats[$cat]=[ordered]@{passed=$p;failed=$f;pending=$q;skipped=$s;score=$score;weight=[double]$m.weights.$cat};if($null-ne$score){$num+=$score*[double]$m.weights.$cat;$den+=[double]$m.weights.$cat}}
$hard+=@($criteria|?{$_.hardGate -and $_.status -eq 'FAIL'}|% id);$pending+=@($criteria|?{$_.status -eq 'PENDING'}|% id);$local=if($infra.Count){'BLOCKED'}elseif($hard.Count){'FAIL'}else{'PASS'};$pendingRequired=$pending.Count -gt 0;$provisional=if($den){[math]::Round($num/$den,2)}else{$null};$final=if(-not $pendingRequired -and $local -eq 'PASS'){$provisional}else{$null};$quality=if($local -eq 'BLOCKED'){'BLOCKED'}elseif($local -eq 'FAIL'){'FAIL'}elseif($pendingRequired){'PROVISIONAL'}elseif($final -ge 95){'VERIFIED'}elseif($final -ge 90){'ACCEPTABLE'}else{'NOT_READY'}
$buildSummary=if($build){[ordered]@{completed=$build.completed;exitCode=$build.exitCode;timedOut=$build.timedOut;command=$build.command}}else{$null};$testSummary=if($test){[ordered]@{completed=$test.completed;exitCode=$test.exitCode;timedOut=$test.timedOut;command=$test.command}}else{$null};$relativeTrx=@($trxFiles|%{ $_.Substring($repo.Length).TrimStart('\','/') -replace '\\','/' });$exec=[ordered]@{build=$buildSummary;fullSuite=$testSummary;trxFiles=$relativeTrx;counts=[ordered]@{total=$combined.total;passed=$combined.passed;failed=$combined.failed;skipped=$combined.skipped};evidenceDirectory='artifacts/quality/<milestone>'};$report=[ordered]@{milestone=$m.milestone;targetCommit=$m.targetCommit;baseReference=$m.baseReference;localStatus=$local;qualityStatus=$quality;repositoryHealth=$repositoryHealth;milestoneRegressionStatus=$milestoneRegressionStatus;infrastructureErrors=$infra;hardGateFailures=$hard;pendingEvidence=$pending;knownFailuresObserved=$knownObserved;newFailures=$newFailures;knownFailuresUnconfirmed=$knownUnconfirmed;criteria=$criteria;requirementCoverage=$summary;categoryScores=$cats;provisionalScore=$provisional;finalQualityScore=$final;testExecution=$exec;platformEvidencePending=@($criteria|?{$_.status -eq 'PENDING' -and $_.evidence.type -eq 'platform evidence'}|% id);efficiency=$m.efficiency}
$json=Join-Path $reportDir 'v1-3-g.local.json';$md=Join-Path $reportDir 'v1-3-g.local.md';$report|ConvertTo-Json -Depth 30|Set-Content $json -Encoding utf8;$lines=@('# V1.3-G Quality Baseline','',"Target commit: $($m.targetCommit)","Status: $quality","Local status: $local",'', '## Category scores','', '| category | passed | failed | pending | score | weight |','|---|---:|---:|---:|---:|---:|');foreach($cat in $Categories){$v=$cats[$cat];$lines += "| $cat | $($v.passed) | $($v.failed) | $($v.pending) | $($v.score) | $($v.weight) |"};$lines+=@('', '## Requirement coverage',"total / pass / fail / pending / skip: $($summary.total) / $($summary.PASS) / $($summary.FAIL) / $($summary.PENDING) / $($summary.SKIP)",'', '## Regression',"build exit: $($build.exitCode)","full tests exit: $($test.exitCode)","TRX counts: $($combined.total) total / $($combined.passed) / $($combined.failed) / $($combined.skipped) skipped", "platform evidence pending: $([string]::Join(', ', $report.platformEvidencePending))",'', '## Efficiency',"workflow: $($m.efficiency.workflowMode)","packet count: $($m.efficiency.packetCount)","quota %: $($m.efficiency.quotaWindowPercent)",'', '## Score',"provisional score: $provisional","final score: $final",'', '## Outstanding evidence');$lines+=@($pending|%{"- $_"});$lines|Set-Content $md -Encoding utf8;Write-Output ("${quality}: local=$local criteria=$($summary.total) PASS=$($summary.PASS) FAIL=$($summary.FAIL) PENDING=$($summary.PENDING) SKIP=$($summary.SKIP) tests=$($combined.total)/$($combined.passed)/$($combined.failed)/$($combined.skipped)");if($local -ne 'PASS' -or ($pendingRequired -and -not $AllowPendingExternal)){exit 1}else{exit 0}
